spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sapsanb1
    hikari:
      schema: money
    username: postgres
    password: 29082021
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update